#ifndef QUQICRYPTO_DEFINITION_HPP
#define QUQICRYPTO_DEFINITION_HPP

#define QUQICRYPTO_NAMESPACE_BEGIN namespace qcrypto {
#define QUQICRYPTO_NAMESPACE_END }

#define PKEY_NAMESPACE_BEGIN namespace pkey {
#define PKEY_NAMESPACE_END }

#endif // !QUQICRYPTO_DEFINITION_HPP
